   #Создание директории для скрипта
 - name: create directory user_directory/bin
   file: path={{ item.destination_path }}/../bin state=directory owner={{ item.user }} group={{ item.user }} mode=0755
   with_items: "{{ backups }}"

 - name: Create the exclude file
   template: src=exclude.txt.j2 dest={{ item.destination_path }}/../bin/exclude_{{ item.name | default(omit) }}.txt owner={{ item.user }} group={{ item.user }} mode=0750
   with_items: "{{ backups }}"

    #Копирование скриптов на сервер
 - name: copy script
   template: src=backup_script.sh.j2 dest={{ item.destination_path }}/../bin/backup_script.sh owner={{ item.user }} group={{ item.user }} mode="ug+x"
   with_items: "{{ backups }}"

   #Создание директории для хранения
 - name: create directory user_directory/backup
   file: path={{ item.destination_path }}/{{ item.name }} state=directory owner={{ item.user }} group={{ item.user }} mode=0755
   with_items: "{{ backups }}"

   #Установка задания крона
 - cron: name="{{ item.name }}" month="{{ item.cron_month }}" weekday="{{ item.cron_weekday }}" day="{{ item.cron_day }}"
         hour="{{ item.cron_hour }}" minute="{{ item.cron_minut }}"  user="{{ item.user }}"
         job="sh {{ item.destination_path }}/../bin/backup_script.sh {{ item.source_path }} {{ item.destination_path }}/{{ item.name }} {{ item.user_db|default("''") }} {{ item.user_db_passwd|default("''") }} {{ item.database|default("''") }} {{ item.days|default(1) }} > /tmp/backup_{{ item.name | default(omit) }}.log 2>&1"
   with_items: "{{ backups }}"

 - name: Check that the /etc/zabbix/zabbix_agentd.conf exists
   stat:
     path: /etc/zabbix/zabbix_agentd.conf
   register: stat_result

 - name: add line to the zabbix
   lineinfile: dest=/etc/zabbix/zabbix_agentd.conf line="UserParameter=backup_monitoring[*],cat /tmp/backup_info"
   ignore_errors: yes
   notify: restart zabbix-agent
   when: stat_result.stat.exists == True 

