# Setup php7
php_fpm_daemon: php7.0-fpm
php_fpm_pools_daemon: php-fpm7.0
php_fpm_conf_path: /etc/php/7.0/fpm
php_fpm_pools_directory: "/etc/php/7.0/fpm/pool.d"
php_extension_conf_paths:
  - /etc/php/7.0/fpm/conf.d
  - /etc/php/7.0/apache2/conf.d
  - /etc/php/7.0/cli/conf.d
php_conf_paths:
  - /etc/php/7.0/fpm
  - /etc/php/7.0/apache2
  - /etc/php/7.0/cli
php_packages:
  - php7.0
  - php7.0-mcrypt
  - php7.0-cli
  - php7.0-common
  - php7.0-curl
  - php7.0-dev
  - php7.0-gd
  - php7.0-mysql
  - php7.0-memcached
  - php7.0-fpm
  - php7.0-dom
  - php7.0-zip
  - php7.0-mbstring

php_enable_webserver: false
php_enable_php_fpm: true
php_enable_apc: false
php_opcache_enabled_in_ini: true
php_opcache_enable: "1"
php_opcache_enable_cli: "0"
php_opcache_memory_consumption: "512"
php_opcache_interned_strings_buffer: "16"
php_opcache_max_accelerated_files: "2048"
php_opcache_max_wasted_percentage: "5"
php_opcache_validate_timestamps: "1"
php_opcache_revalidate_freq: "0"
php_opcache_max_file_size: "0"


php_memory_limit: "128M"
php_max_execution_time: "120"
php_post_max_size: "128M"
php_upload_max_filesize: "128M"
php_date_timezone: "Europe/Moscow"
php_sendmail_path: "/usr/sbin/sendmail -t -i"
php_short_open_tag: false
php_expose_php: "off"
php_disable_functions:
  - popen
  - exec
  - ftp_exec
  - system
  - passthru
  - proc_open
  - shell_exec
  - phpinfo
