---
# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
    
- include: create_pool.yml
  when: site_status == "present"

- include: remove_pool.yml
  when: site_status == "absent"
