# Ansible managed

- hosts: localhost
  user: root
  become: no
  vars_files:
# Setup variables
    - vars/users.yml
    - vars/directories.yml
# Setup roles
  roles:
    - weareinteractive.users
    - initlabopen.generic_directories
